version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    # ports:
      # - 80:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.open-suite.rule=Host(`ff3.dev01.minhtuanvu.com`)
      - traefik.http.routers.open-suite.entrypoints=websecure
      - traefik.http.routers.open-suite.tls.certresolver=myresolver
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db:
